export const accountsContent = {
  listTitle: "Cuentas",
  addAccount: "Agregar cuenta",
  newTitle: "Nueva cuenta",
  newMetaTitle: "Nueva cuenta — Finza",
  newMetaDescription: "Agregá una cuenta en pesos o en dólares. El saldo se muestra en su moneda.",
  editTitle: "Editar cuenta",
  editMetaTitle: "Editar cuenta — Finza",
  editMetaDescription: "Cambiá el nombre, el tipo o el saldo inicial de una cuenta.",
  backToList: "Volver a cuentas",
  emptyTitle: "Cuentas",
  emptyBody: "Todavía no tenés cuentas. Cuando agregues una, vas a ver el saldo en su moneda.",
  groupArs: "Pesos",
  groupUsd: "Dólares",
  archivedHeading: "Archivadas",
  archivedBadge: "Archivada",
  nameLabel: "Nombre",
  namePlaceholder: "Galicia, Mercado Pago, Efectivo…",
  typeLabel: "Tipo",
  currencyLabel: "Moneda",
  balanceLabel: "Saldo inicial",
  balancePlaceholder: "0,00",
  balanceHint: "Punto para los miles, coma para los centavos. Ej.: 3.016.407,99",
  ledgerLockedHint: "El saldo inicial y la moneda ya no se pueden cambiar porque hay movimientos.",
  currencyPrefixes: {
    ARS: "$",
    USD: "US$",
  },
  notesLabel: "Notas",
  notesOptional: "Opcional",
  types: {
    banco: "Banco",
    billetera: "Billetera",
    efectivo: "Efectivo",
    otro: "Otro",
  },
  currencies: {
    ARS: "Pesos",
    USD: "Dólares",
  },
  submitCreate: "Guardar cuenta",
  pendingCreate: "Guardando…",
  submitEdit: "Guardar cambios",
  pendingEdit: "Guardando…",
  historyTitle: "Movimientos de esta cuenta",
  historyEmpty: "Todavía no hay movimientos en esta cuenta.",
  historyCaption: "Historial de esta cuenta",
  archive: "Archivar",
  archiveConfirm:
    "¿Archivar esta cuenta? No se borra: deja de aparecer para usar. El historial queda acá y la podés restaurar.",
  archiveConfirmCta: "Sí, archivar",
  archiveCancel: "Cancelar",
  restore: "Restaurar",
  errors: {
    invalidInput: "Revisá los datos e intentá de nuevo.",
    emptyName: "Escribí el nombre de la cuenta.",
    nameTooLong: "El nombre es demasiado largo.",
    emptyType: "Elegí el tipo de cuenta.",
    emptyCurrency: "Elegí la moneda.",
    emptyBalance: "Escribí el saldo.",
    invalidBalance: "Ese saldo no parece un número.",
    notesTooLong: "La nota es demasiado larga.",
    notFound: "No encontramos esa cuenta.",
    tooMany: "Llegaste al máximo de cuentas por ahora.",
    generic: "No se pudo guardar. Probá de nuevo.",
  },
} as const;
