export const authContent = {
  loginTitle: "Iniciar sesión en Finza",
  loginDescription: "Iniciá sesión para ver tu situación financiera.",
  registerTitle: "Crear cuenta en Finza",
  registerDescription: "Registrate con email y contraseña para empezar.",
  brand: "Finza",
  brandEyebrow: "Finanzas personales",
  brandPanelTitle: "Conocé tus finanzas.",
  brandPanelBody: "Entendé. Controlá. Decidí.",
  brandCardsAria: "Tarjeta. Activar para dar vuelta.",
  loginHeading: "Iniciar sesión en Finza",
  loginLead: "",
  registerHeading: "Crear cuenta en Finza",
  registerLead: "",
  nameLabel: "Nombre",
  emailLabel: "Email",
  passwordLabel: "Contraseña",
  passwordHint: "Mínimo 8 caracteres.",
  showPassword: "Mostrar contraseña",
  hidePassword: "Ocultar contraseña",
  submitLogin: "Entrar a Finza",
  submitRegister: "Crear mi cuenta",
  pendingLogin: "Entrando…",
  pendingRegister: "Creando cuenta…",
  googleCta: "Continuar con Google",
  orGoogle: "o con Google",
  noAccount: "¿No tenés cuenta?",
  hasAccount: "¿Ya tenés cuenta?",
  goRegister: "Crear cuenta",
  goLogin: "Entrar",
  homeLogin: "Entrar",
  homeRegister: "Crear cuenta",
  errors: {
    invalidCredentials: "Email o contraseña incorrectos.",
    emailTaken: "Ya existe una cuenta con ese email.",
    rateLimited: "Demasiados intentos. Probá de nuevo en unos minutos.",
    invalidEmail: "Ese email no parece válido.",
    emptyName: "Escribí tu nombre.",
    emptyEmail: "Escribí tu email.",
    emptyPassword: "Escribí tu contraseña.",
    passwordTooShort: "La contraseña tiene que tener al menos 8 caracteres.",
    passwordTooLong: "La contraseña es demasiado larga.",
    nameTooLong: "El nombre es demasiado largo.",
    invalidInput: "Revisá los datos e intentá de nuevo.",
    generic: "No se pudo completar. Probá de nuevo.",
    passwordAccount:
      "Este email ya tiene cuenta con contraseña. Entrá con email y contraseña.",
    oauth: "No se pudo entrar con Google. Probá de nuevo o usá email y contraseña.",
  },
} as const;
