export const cardsContent = {
  listTitle: "Tarjetas",
  addCard: "Agregar tarjeta",
  newTitle: "Nueva tarjeta",
  newMetaTitle: "Nueva tarjeta — Finza",
  newMetaDescription:
    "Agregá una tarjeta: límite, cierre, vencimiento y la cuenta con la que la pagás.",
  editTitle: "Tarjeta",
  editMetaTitle: "Tarjeta — Finza",
  editMetaDescription: "Deuda, disponible, ciclo y datos de una tarjeta.",
  backToList: "Volver a tarjetas",
  emptyTitle: "Tarjetas",
  emptyBody: "Todavía no tenés tarjetas. Cuando agregues una, vas a ver el límite, la deuda y los vencimientos.",
  emptyNoAccountsBody: "Primero agregá una cuenta. Con esa cuenta vas a pagar la tarjeta.",
  addAccount: "Agregar cuenta",
  groupArs: "Pesos",
  groupUsd: "Dólares",
  archivedHeading: "Archivadas",
  archivedBadge: "Archivada",
  lastFourPrefix: "••••",
  nameLabel: "Nombre",
  namePlaceholder: "Visa Galicia, Mercado Pago…",
  brandLabel: "Marca",
  lastFourLabel: "Últimos 4",
  lastFourPlaceholder: "1234",
  currencyLabel: "Moneda",
  limitLabel: "Límite",
  limitPlaceholder: "0,00",
  limitHint: "Punto para los miles, coma para los centavos. Ej.: 1.500.000,00",
  closeDayLabel: "Día de cierre",
  dueDayLabel: "Día de vencimiento",
  paymentAccountLabel: "Cuenta de pago",
  paymentAccountPlaceholder: "Elegí una cuenta",
  paymentAccountHint: "Tiene que ser de la misma moneda que la tarjeta.",
  notesLabel: "Notas",
  notesOptional: "Opcional",
  ledgerLockedHint: "La moneda ya no se puede cambiar porque hay movimientos.",
  brands: {
    visa: "Visa",
    mastercard: "Mastercard",
    amex: "American Express",
    naranja: "Naranja",
    otra: "Otra",
  },
  currencies: {
    ARS: "Pesos",
    USD: "Dólares",
  },
  submitCreate: "Guardar tarjeta",
  pendingCreate: "Guardando…",
  submitEdit: "Guardar cambios",
  pendingEdit: "Guardando…",
  archive: "Archivar",
  archiveConfirm:
    "¿Archivar esta tarjeta? No se borra: deja de aparecer para usar. Los consumos y pagos quedan en el libro y la podés restaurar.",
  archiveConfirmCta: "Sí, archivar",
  archiveCancel: "Cancelar",
  restore: "Restaurar",
  debtLabel: "Deuda",
  availableLabel: "Disponible",
  limitStatLabel: "Límite",
  dueNowLabel: "A pagar ahora",
  openCycleLabel: "Consumo del ciclo abierto",
  nextCloseLabel: "Próximo cierre",
  nextDueLabel: "Próximo vencimiento",
  overLimitHint: "La deuda supera el límite. El banco a veces lo autoriza igual.",
  registerSpend: "Registrar consumo",
  payCard: "Pagar",
  viewDebt: "Ver deuda",
  debtCompositionTitle: "Composición de la deuda",
  debtCompositionEmpty: "Esta tarjeta no tiene deuda.",
  debtCompositionTotal: "Total",
  singlePayment: "1 pago",
  installmentsHeading: "Compras en cuotas",
  viewInstallments: "Ver cuotas",
  closeInstallments: "Cerrar",
  paidBadge: "Pagada",
  installmentOf: (number: number, count: number) => `${number} de ${count}`,
  installmentDue: "Vence",
  purchaseCount: (count: number) => `${count} cuotas`,
  noCategory: "Sin categoría",
  errors: {
    invalidInput: "Revisá los datos e intentá de nuevo.",
    emptyName: "Escribí el nombre de la tarjeta.",
    nameTooLong: "El nombre es demasiado largo.",
    emptyBrand: "Elegí la marca.",
    emptyLastFour: "Escribí los últimos 4 números.",
    invalidLastFour: "Tienen que ser 4 dígitos.",
    emptyCurrency: "Elegí la moneda.",
    emptyLimit: "Escribí el límite.",
    invalidLimit: "Ese límite no parece un número.",
    zeroLimit: "El límite tiene que ser mayor a cero.",
    emptyCloseDay: "Elegí el día de cierre.",
    emptyDueDay: "Elegí el día de vencimiento.",
    emptyPaymentAccount: "Elegí la cuenta de pago.",
    notesTooLong: "La nota es demasiado larga.",
    notFound: "No encontramos esa tarjeta.",
    tooMany: "Llegaste al máximo de tarjetas por ahora.",
    paymentCurrency: "La cuenta de pago tiene que ser de la misma moneda que la tarjeta.",
    paymentUnavailable: "Esa cuenta no está disponible.",
    generic: "No se pudo guardar. Probá de nuevo.",
  },
} as const;
