export const metasContent = {
  listTitle: "Metas",
  addGoal: "Agregar objetivo",
  emptyTitle: "Metas",
  emptyBody: "Todavía no tenés objetivos de ahorro. Cuando armes uno, vas a ver el progreso acá.",
  newTitle: "Nuevo objetivo",
  newMetaTitle: "Nuevo objetivo — Finza",
  newMetaDescription: "Armá un objetivo de ahorro. Asignar plata baja lo libre; no mueve las cuentas.",
  editTitle: "Objetivo",
  editMetaTitle: "Objetivo — Finza",
  editMetaDescription: "Progreso, asignar y editar un objetivo de ahorro.",
  backToList: "Volver a metas",
  nameLabel: "Nombre",
  namePlaceholder: "Vacaciones, fondo, reserva…",
  targetLabel: "Monto objetivo",
  assignedNowLabel: "Asignar ahora",
  assignedNowHint: "Opcional. No mueve plata de las cuentas: baja lo libre de esa moneda.",
  amountPlaceholder: "0,00",
  amountHint: "Punto para los miles, coma para los centavos. Ej.: 2.000.000",
  currencyLabel: "Moneda",
  targetMonthLabel: "Mes objetivo",
  submitCreate: "Guardar objetivo",
  pendingCreate: "Guardando…",
  submitEdit: "Guardar cambios",
  pendingEdit: "Guardando…",
  assignLabel: "Asignar",
  assignHint: "Suma a lo ya reservado. Las cuentas no cambian; baja lo libre.",
  submitAssign: "Asignar",
  pendingAssign: "Asignando…",
  assignedOf: (assigned: string, target: string) => `${assigned} de ${target}`,
  remainingLabel: "Faltante",
  monthlyNeededLabel: "Por mes para llegar",
  dueLabel: "Para",
  freeLabel: "Libre en esta moneda",
  noPace: "Sin ritmo suficiente para estimar una fecha.",
  reachedEyebrow: "Alcanzado",
  pausedEyebrow: "Pausado",
  statuses: {
    activo: "Activo",
    alcanzado: "Alcanzado",
    pausado: "Pausado",
    cancelado: "Cancelado",
  },
  pause: "Pausar",
  resume: "Reanudar",
  release: "Liberar",
  releaseHint: "Deja de restar de lo libre. El objetivo sigue marcado como alcanzado.",
  cancel: "Cancelar objetivo",
  cancelConfirm: "Se libera lo asignado y el objetivo deja de verse. Las cuentas no cambian.",
  cancelConfirmCta: "Sí, cancelar",
  cancelAbort: "Seguir con el objetivo",
  errors: {
    invalidInput: "Revisá los datos e intentá de nuevo.",
    emptyName: "Poné un nombre.",
    emptyTarget: "Poné el monto que querés alcanzar.",
    invalidTarget: "El monto objetivo no es válido.",
    invalidAssigned: "El monto a asignar no es válido.",
    emptyAmount: "Poné cuánto querés asignar.",
    invalidAmount: "El monto a asignar no es válido.",
    emptyMonth: "Elegí el mes en el que querés llegar.",
    emptyCurrency: "Elegí pesos o dólares.",
    tooMany: "Llegaste al máximo de objetivos. Cancelá alguno para agregar otro.",
    notFound: "Ese objetivo ya no está.",
    generic: "No se pudo guardar. Intentá de nuevo.",
  },
} as const;
