export const movementsContent = {
  listTitle: "Movimientos",
  addMovement: "Registrar movimiento",
  newTitle: "Nuevo movimiento",
  newMetaTitle: "Nuevo movimiento — Finza",
  newMetaDescription: "Registrá un gasto, un ingreso, un pago de tarjeta u otro movimiento.",
  backToList: "Volver a movimientos",
  emptyTitle: "Movimientos",
  emptyBody: "Todavía no hay movimientos. Cuando registres uno, van a aparecer acá.",
  emptyNoAccountsBody: "Primero agregá una cuenta. Después vas a poder registrar movimientos.",
  addAccount: "Agregar cuenta",
  tableCaption: "Libro de movimientos",
  searchLabel: "Buscar",
  searchPlaceholder: "Fecha, cuenta, categoría, importe, nota…",
  filters: "Filtros",
  filtersTitle: "Filtros",
  filtersApply: "Ver resultados",
  filtersClear: "Quitar filtros",
  filtersClose: "Cerrar",
  amountFrom: "Desde",
  amountTo: "Hasta",
  dateFrom: "Desde",
  dateTo: "Hasta",
  allAccounts: "Todas",
  allCategories: "Todas",
  allTypes: "Todos",
  noCategoryOption: "Sin categoría",
  noResultsTitle: "Nada coincide",
  noResultsBody: "Probá otra búsqueda o quitá los filtros.",
  colDate: "Fecha",
  colType: "Tipo",
  colCategory: "Categoría",
  colAccount: "Cuenta",
  filterAccountLabel: "Cuenta o tarjeta",
  colAmount: "Importe",
  colActions: "Acciones",
  noCategory: "—",
  voidedBadge: "Anulado",
  viewNote: "Ver nota",
  closeNote: "Cerrar",
  types: {
    gasto: "Gasto",
    ingreso: "Ingreso",
    transferencia: "Transferencia",
    conversion: "Conversión",
    ajuste: "Ajuste",
    pago_tarjeta: "Pago de tarjeta",
  },
  typeLabel: "Tipo",
  paidWithLabel: "¿Con qué lo pagaste?",
  paidWith: {
    cuenta: "Cuenta",
    tarjeta: "Tarjeta",
  },
  cardLabel: "Tarjeta",
  cardPlaceholder: "Elegí una tarjeta",
  creditHint: "No baja el saldo de ninguna cuenta. Suma deuda en la tarjeta.",
  cardPaymentHint: "Baja el saldo de la cuenta y la deuda. No es un gasto nuevo.",
  paymentMonthLabel: "Cuota de este mes",
  paymentMonthCustom: "Escribir el importe",
  paymentMonthDueNow: (amount: string) => `Lo que vence ahora · ${amount}`,
  paymentMonthStatement: (date: string, amount: string) =>
    `Este vencimiento (${date}) · ${amount}`,
  paymentMonthInstallment: (title: string, number: number, count: number, amount: string) =>
    `${title} · ${number} de ${count} · ${amount}`,
  paymentMonthHint:
    "Elegí la cuota para completar el importe, o escribilo vos. Se cubre primero lo más viejo.",
  overLimitHint: "Con este importe te pasás del límite. Se puede guardar igual.",
  installmentCountLabel: "Cuotas",
  installmentCountHint: "Sin interés. 1 es un solo pago.",
  installmentEqualHint: (count: number, each: string) =>
    `${count} cuotas de ${each}. La deuda sube por el total hoy.`,
  installmentRemainderHint: (count: number, each: string, last: string) =>
    `${count - 1} cuotas de ${each} y la última de ${last}. La deuda sube por el total hoy.`,
  installmentsSuffix: (count: number) => `${count} cuotas`,
  accountLabel: "Cuenta",
  accountFromLabel: "Sale de",
  accountToLabel: "Entra en",
  accountPlaceholder: "Elegí una cuenta",
  categoryLabel: "Categoría",
  categoryPlaceholder: "Elegí una categoría",
  amountLabel: "Importe",
  amountFromLabel: "Importe que sale",
  amountToLabel: "Importe que entra",
  amountPlaceholder: "0,00",
  amountHint: "Punto para los miles, coma para los centavos. Ej.: 150.000,00",
  observedLabel: "Saldo que ves ahora",
  observedHint: "El de la app del banco o de la billetera, no el de Finza.",
  currentBalance: "En Finza esta cuenta tiene",
  differenceUp: "Van a entrar",
  differenceDown: "Van a salir",
  dateLabel: "Fecha",
  notesLabel: "Nota",
  notesOptional: "Opcional",
  reasonLabel: "Motivo",
  rateHint: (from: string, to: string) =>
    `Cotización implícita: ${from} = ${to}. No se guarda.`,
  submit: "Guardar movimiento",
  pending: "Guardando…",
  void: "Anular",
  voidConfirm:
    "¿Anular este movimiento? Deja de contar en los saldos y en Libre. Sigue en el libro, marcado como anulado.",
  voidConfirmCta: "Sí, anular",
  voidCancel: "Cancelar",
  voidPending: "Anulando…",
  errors: {
    invalidInput: "Revisá los datos e intentá de nuevo.",
    emptyType: "Elegí el tipo de movimiento.",
    emptyAccount: "Elegí la cuenta.",
    emptyCard: "Elegí la tarjeta.",
    emptyCounterAccount: "Elegí la cuenta de destino.",
    emptyCategory: "Elegí la categoría.",
    emptyAmount: "Escribí el importe.",
    invalidAmount: "Ese importe no parece un número.",
    zeroAmount: "El importe tiene que ser mayor a cero.",
    emptyObserved: "Escribí el saldo que ves ahora.",
    invalidObserved: "Ese saldo no parece un número.",
    emptyDate: "Elegí la fecha.",
    invalidDate: "Esa fecha no es válida.",
    futureDate: "La fecha no puede ser posterior a hoy.",
    notesTooLong: "La nota es demasiado larga.",
    emptyReason: "Escribí el motivo del ajuste.",
    accountUnavailable: "Esa cuenta no está disponible.",
    cardUnavailable: "Esa tarjeta no está disponible.",
    categoryUnavailable: "Esa categoría no coincide con el tipo de movimiento.",
    sameAccount: "Elegí dos cuentas distintas.",
    currencyMismatch: "Tiene que ser entre cuentas o una tarjeta de la misma moneda.",
    conversionSameCurrency: "La conversión es entre pesos y dólares. Si son la misma moneda, usá una transferencia.",
    noAjuste: "Ese saldo es el mismo que ya tiene Finza. No hace falta un ajuste.",
    paymentExceedsDebt: "El pago no puede ser mayor a la deuda de la tarjeta.",
    invalidInstallments: "Las cuotas tienen que ser un número entre 1 y 36.",
    tooMany: "Llegaste al máximo de movimientos por ahora.",
    notFound: "No encontramos ese movimiento.",
    alreadyVoided: "Ese movimiento ya está anulado.",
    generic: "No se pudo guardar. Probá de nuevo.",
    voidGeneric: "No se pudo anular. Probá de nuevo.",
  },
} as const;
