export const perfilContent = {
  masLink: "Perfil",
  masLinkHint: "Tu nombre, la moneda por defecto y si los objetivos restan de Libre.",
  title: "Perfil",
  metaTitle: "Perfil — Finza",
  metaDescription: "Cambiá tu nombre, la moneda por defecto y si lo asignado a objetivos resta de Libre.",
  backToMas: "Volver a Más",
  nameLabel: "Nombre",
  emailLabel: "Email",
  emailHint: "El email no se puede cambiar.",
  currencyLabel: "Moneda por defecto",
  currencyHint: "Se usa cuando agregás una cuenta, una tarjeta, un objetivo o un presupuesto.",
  currencies: {
    ARS: "Pesos",
    USD: "Dólares",
  },
  goalsLabel: "Objetivos y Libre",
  goalsHint:
    "Si está encendido, lo asignado a un objetivo activo resta de Libre. Las cuentas no cambian.",
  goalsOn: "Restar de Libre",
  goalsOff: "No restar de Libre",
  submit: "Guardar cambios",
  pending: "Guardando…",
  saved: "Listo. Guardamos los cambios.",
  errors: {
    invalidInput: "Revisá los datos e intentá de nuevo.",
    emptyName: "Escribí tu nombre.",
    nameTooLong: "El nombre es demasiado largo.",
    emptyCurrency: "Elegí la moneda por defecto.",
    emptyGoals: "Elegí si los objetivos restan de Libre.",
    notFound: "No encontramos tu perfil.",
    generic: "No se pudo guardar. Probá de nuevo.",
  },
} as const;
