export const planificacionContent = {
  listTitle: "Planificación",
  addRule: "Agregar recurrente",
  newTitle: "Nuevo recurrente",
  newMetaTitle: "Nuevo recurrente — Finza",
  newMetaDescription: "Armá un gasto o un ingreso que se repite: sueldo, alquiler, Netflix.",
  editTitle: "Recurrente",
  editMetaTitle: "Recurrente — Finza",
  editMetaDescription: "Editá un gasto o ingreso que se repite.",
  backToList: "Volver a planificación",
  emptyTitle: "Planificación",
  emptyBody: "Todavía no tenés recurrentes. Cuando armes uno, vas a confirmar u omitir cada mes.",
  emptyNoAccountsBody: "Primero agregá una cuenta. Después vas a poder armar recurrentes.",
  addAccount: "Agregar cuenta",
  tabListLabel: "Secciones de planificación",
  tabCalendario: "Calendario",
  tabRecurrentes: "Recurrentes",
  tabPresupuestos: "Presupuestos",
  monthHeading: "Recurrentes del mes",
  monthEmpty: "Este mes no hay recurrentes para confirmar u omitir.",
  rulesHeading: "Tus recurrentes",
  rulesEmpty: "Todavía no tenés recurrentes.",
  nameLabel: "Nombre",
  namePlaceholder: "Netflix, alquiler, sueldo…",
  kindLabel: "Tipo",
  kinds: {
    gasto: "Gasto",
    ingreso: "Ingreso",
  },
  classLabel: "Clase",
  classes: {
    suscripcion: "Suscripción",
    servicio: "Servicio",
    alquiler: "Alquiler",
    envio_tercero: "Envío a alguien",
    sueldo: "Sueldo",
    otro: "Otro",
  },
  amountLabel: "Importe",
  amountPlaceholder: "0,00",
  amountHint: "Punto para los miles, coma para los centavos. Ej.: 15.000,00",
  frequencyLabel: "Cada cuánto",
  frequencies: {
    semanal: "Cada semana",
    mensual: "Cada mes",
    anual: "Cada año",
  },
  dueDayLabel: "Día",
  dueDayWeeklyLabel: "Día de la semana",
  dueMonthLabel: "Mes",
  weekdays: {
    1: "Lunes",
    2: "Martes",
    3: "Miércoles",
    4: "Jueves",
    5: "Viernes",
    6: "Sábado",
    7: "Domingo",
  },
  months: {
    1: "Enero",
    2: "Febrero",
    3: "Marzo",
    4: "Abril",
    5: "Mayo",
    6: "Junio",
    7: "Julio",
    8: "Agosto",
    9: "Septiembre",
    10: "Octubre",
    11: "Noviembre",
    12: "Diciembre",
  },
  paidWithLabel: "¿Con qué se paga?",
  paidWith: {
    cuenta: "Cuenta",
    tarjeta: "Tarjeta",
  },
  accountLabel: "Cuenta",
  cardLabel: "Tarjeta",
  accountPlaceholder: "Elegí una cuenta",
  cardPlaceholder: "Elegí una tarjeta",
  categoryLabel: "Categoría",
  categoryPlaceholder: "Elegí una categoría",
  startsOnLabel: "Desde",
  endsOnLabel: "Hasta",
  endsOnOptional: "Opcional",
  submitCreate: "Guardar recurrente",
  pendingCreate: "Guardando…",
  submitEdit: "Guardar cambios",
  pendingEdit: "Guardando…",
  confirm: "Confirmar",
  omit: "Omitir",
  confirmedBadge: "Confirmada",
  omittedBadge: "Omitida",
  overdueBadge: "Vencida",
  scheduledBadge: "Pendiente",
  pausedBadge: "Pausada",
  frequencyCaption: (frequency: "semanal" | "mensual" | "anual", dueDay: number, dueMonth: number | null) => {
    if (frequency === "semanal") {
      return `Cada ${planificacionContent.weekdays[dueDay as 1 | 2 | 3 | 4 | 5 | 6 | 7]}`;
    }
    if (frequency === "anual" && dueMonth) {
      return `${dueDay} de ${planificacionContent.months[dueMonth as keyof typeof planificacionContent.months]}`;
    }
    return `Día ${dueDay} de cada mes`;
  },
  pause: "Pausar",
  resume: "Reanudar",
  deleteRule: "Eliminar",
  deleteConfirm: "¿Eliminar este recurrente? Los movimientos ya confirmados siguen en el libro. Las fechas futuras pendientes se sacan.",
  deleteConfirmCta: "Sí, eliminar",
  deleteCancel: "Cancelar",
  creditHint: "Al confirmar, suma deuda en la tarjeta. No baja el saldo de una cuenta.",
  accountHint: "Al confirmar, se registra el movimiento en esa cuenta.",
  errors: {
    invalidInput: "Revisá los datos e intentá de nuevo.",
    emptyName: "Escribí un nombre.",
    nameTooLong: "El nombre es demasiado largo.",
    emptyKind: "Elegí si es gasto o ingreso.",
    emptyClass: "Elegí la clase.",
    emptyAmount: "Escribí el importe.",
    invalidAmount: "Ese importe no parece un número.",
    emptyFrequency: "Elegí cada cuánto se repite.",
    emptyDueDay: "Elegí el día.",
    emptyDueMonth: "Elegí el mes.",
    emptyAccount: "Elegí la cuenta.",
    emptyCard: "Elegí la tarjeta.",
    emptyCategory: "Elegí la categoría.",
    emptyStartsOn: "Elegí desde cuándo.",
    invalidDate: "Esa fecha no es válida.",
    endsBeforeStart: "La fecha hasta no puede ser anterior a desde.",
    accountUnavailable: "Esa cuenta no está disponible.",
    cardUnavailable: "Esa tarjeta no está disponible.",
    categoryUnavailable: "Esa categoría no coincide con el tipo.",
    tooMany: "Llegaste al máximo de recurrentes por ahora.",
    notFound: "No encontramos ese recurrente.",
    alreadyClosed: "Esa fecha ya está confirmada u omitida.",
    generic: "No se pudo guardar. Probá de nuevo.",
    actionGeneric: "No se pudo completar. Probá de nuevo.",
  },
  addBudget: "Agregar presupuesto",
  budgetsHeading: "Presupuestos",
  budgetsEmpty: "Todavía no hay un tope para este mes. El pago de tarjeta no cuenta acá.",
  budgetsHint:
    "En crédito, cuenta la cuota de este mes, no el total de la compra. El pago de la tarjeta no entra.",
  calendarHeading: "Calendario",
  calendarEmpty: "Este mes no hay recurrentes ni vencimientos de tarjeta.",
  dayEmpty: "Este día no tiene vencimientos ni recurrentes.",
  prevMonth: "Mes anterior",
  nextMonth: "Mes siguiente",
  newBudgetTitle: "Nuevo presupuesto",
  newBudgetMetaTitle: "Nuevo presupuesto — Finza",
  newBudgetMetaDescription: "Poné un tope de gasto por categoría para un mes, en pesos o en dólares.",
  editBudgetTitle: "Presupuesto",
  editBudgetMetaTitle: "Presupuesto — Finza",
  editBudgetMetaDescription: "Cambiá el tope de gasto de una categoría en un mes.",
  budgetAmountLabel: "Tope",
  budgetMonthLabel: "Mes",
  budgetCurrencyLabel: "Moneda",
  budgetCategoryHint: "Si elegís una categoría padre, también cuenta lo de sus subcategorías.",
  submitCreateBudget: "Guardar presupuesto",
  pendingCreateBudget: "Guardando…",
  submitEditBudget: "Guardar cambios",
  pendingEditBudget: "Guardando…",
  deleteBudget: "Eliminar",
  deleteBudgetConfirm: "¿Eliminar este presupuesto? Los gastos ya registrados siguen en el libro.",
  deleteBudgetConfirmCta: "Sí, eliminar",
  deleteBudgetCancel: "Cancelar",
  usedOf: (used: string, cap: string) => `${used} de ${cap}`,
  alertOk: "Dentro del tope",
  alertWarn: "Alerta",
  alertOver: "Excedido",
  weekdayShort: ["L", "M", "X", "J", "V", "S", "D"] as const,
  cardDueKind: "Vencimiento de tarjeta",
  viewCard: "Ver tarjeta",
  recurrenceKind: "Recurrente",
  budgetErrors: {
    invalidInput: "Revisá los datos e intentá de nuevo.",
    emptyCategory: "Elegí una categoría.",
    emptyMonth: "Elegí el mes.",
    emptyAmount: "Escribí el tope.",
    invalidAmount: "Ese tope no parece un número.",
    emptyCurrency: "Elegí la moneda.",
    categoryUnavailable: "Esa categoría no está disponible para un gasto.",
    duplicate: "Ya hay un presupuesto para esa categoría, mes y moneda.",
    tooMany: "Llegaste al máximo de presupuestos por ahora.",
    notFound: "No encontramos ese presupuesto.",
    generic: "No se pudo guardar. Probá de nuevo.",
  },
} as const;
